In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [3]:
# manually define project root
PROJECT_ROOT = Path("/Users/shreechatterjee/jak-selectivity-screening")

# set working directory
os.chdir(PROJECT_ROOT)

print(os.getcwd())

/Users/shreechatterjee/jak-selectivity-screening

In [11]:
fda = pd.read_csv("data/fda.csv")

In [13]:
fda

               zinc_id                                             smiles
0     ZINC000003831551                            C[C@@H](S)C(=O)NCC(=O)O
1     ZINC000000000353                             COc1ccccc1OC[C@H](O)CO
2     ZINC000003815424  C#C[C@]1(O)CC[C@H]2[C@@H]3CCc4cc(OC)ccc4[C@H]3...
3     ZINC000003872994  CC(=O)N1CCN(c2ccc(OC[C@H]3CO[C@@](Cn4ccnc4)(c4...
4     ZINC000058581064  C[C@@H]1CCO[C@H]2Cn3cc(C(=O)NCc4ccc(F)cc4F)c(=...
...                ...                                                ...
1610  ZINC000261527196  CCN(CC)CCS(=O)(=O)[C@@H]1CCN2C(=O)c3coc(n3)CC(...
1611  ZINC000019364219                       CC[C@@H](CO)NCCN[C@@H](CC)CO
1612  ZINC000169621231  CO[C@H]1C[C@H]2CC[C@H](C)[C@](O)(O2)C(=O)C(=O)...
1613  ZINC000014210455  CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H...
1614  ZINC000253387843  C[C@@H]1OC(=O)C[C@H](O)C[C@H](O)CC[C@@H](O)[C@...

[1615 rows x 2 columns]

In [15]:
top_5pct = pd.read_csv("results/qsar_screen/top_5pct.csv")

In [17]:
top_5pct

,zinc_id,smiles,predicted_delta_pIC50,QSAR_rank
0,ZINC000043100953,Cn1nnc(-c2ccc(-c3ccc(N4C[C@H](COP(=O)(O)O)OC4=...,0.552271,1
1,ZINC000028973446,O=C(O)[C@H]1N=C(c2ccccc2)c2cc(Cl)ccc2NC1=O,0.547649,2
2,ZINC000036701290,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,0.534779,3
3,ZINC000030691797,N#Cc1ccccc1-c1cc(-c2ccccn2)cn(-c2ccccc2)c1=O,0.513548,4
4,ZINC000001530886,CCCc1nc2c(C)cc(-c3nc4ccccc4n3C)cc2n1Cc1ccc(-c2...,0.512924,5
...,...,...,...,...
76,ZINC000000005423,Cc1nc(-c2ccc(OCC(C)C)c(C#N)c2)sc1C(=O)O,-0.027716,77
77,ZINC000000020245,CN(C)CCCN1c2ccccc2CCc2ccccc21,-0.030941,78
78,ZINC000000075126,Cc1nccn1C[C@@H]1CCc2c(c3ccccc3n2C)C1=O,-0.031989,79
79,ZINC000072318121,CCN1CCN(Cc2ccc(Nc3ncc(F)c(-c4cc(F)c5nc(C)n(C(C...,-0.033565,80
80,ZINC000000601317,N#CC(CCN1CCC(C(=O)O)(c2ccccc2)CC1)(c1ccccc1)c1...,-0.033602,81

In [5]:
coconut = pd.read_csv("data/coconut_1_violations.csv")

/var/folders/jn/0kbctjzn2tl1p83gh95ymtw00000gn/T/ipykernel_76466/3078198507.py:1: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  coconut = pd.read_csv("data/coconut_1_violations.csv")

In [9]:
coconut = coconut[["identifier", "canonical_smiles"]]

In [11]:
coconut

          identifier                                   canonical_smiles
0       CNP0366806.5   COC1=CC=CC=C1C(CC/N=C/C1=CC=CC=C1)C1CCOC(C)(C)C1
1       CNP0277601.1  C#CCNC(=O)CC(C1=CC=C(OC)C=C1)C1=C(O)C=C2/C=C/C...
2       CNP0210157.1  COC1=CC=C(/C=C/C(=O)OC(C)C(=O)[C@H]2C[C@]2(C)[...
3       CNP0016509.1  COC1=CC=CC(C2=CC=C3C(=O)N(C)[C@@H]4CN(C(=O)C5C...
4       CNP0224906.1  CN1CCN(C[C@@H]2OC[C@H](NC3CC4=CC=CC=C4C3)[C@H]...
...              ...                                                ...
504271  CNP0408142.1  COC1=CC=C(/C=C2\OC3=C(C=CC4=C3C(C3=CC=CN=C3)CC...
504272  CNP0131204.5  O=C(O)CCC/C=C/C(C1=CC=CC=C1)C1=C(O)C=C2OC(C3=C...
504273  CNP0253092.1            C=C(C(=O)O)[C@H]1C/C=C(\C)CC/C=C(/C)CC1
504274  CNP0213766.1  C=C1C(=O)O[C@@H]2/C=C(/C)CC/C=C(/C)[C@@H](OC(=...
504275  CNP0170984.1  C/C(NCCSSCCN/C(C)=C1\C(=O)C[C@@H]2[C@H]1C2(C)C...

[504276 rows x 2 columns]

In [14]:
coconut.to_csv("data/coconut.csv")